"""empty message

Revision ID: 3dd83a5ecd04
Revises: 8d3e979ba3c7
Create Date: 2022-06-13 13:45:24.333170

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = "3dd83a5ecd04"
down_revision = "8d3e979ba3c7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.add_column(
        "movie_showtimes", sa.Column("cinema_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(None, "movie_showtimes", "cinemas", ["cinema_id"], ["id"])
    op.add_column(
        "tickets", sa.Column("movie_showtime_id", sa.Integer(), nullable=False)
    )
    op.drop_constraint("tickets_cinema_id_fkey", "tickets", type_="foreignkey")
    op.drop_constraint("tickets_movie_id_fkey", "tickets", type_="foreignkey")
    op.create_foreign_key(
        None, "tickets", "movie_showtimes", ["movie_showtime_id"], ["id"]
    )
    op.drop_column("tickets", "movie_id")
    op.drop_column("tickets", "cinema_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tickets",
        sa.Column("cinema_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "tickets",
        sa.Column("movie_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "tickets", type_="foreignkey")
    op.create_foreign_key(
        "tickets_movie_id_fkey", "tickets", "movies", ["movie_id"], ["id"]
    )
    op.create_foreign_key(
        "tickets_cinema_id_fkey", "tickets", "cinemas", ["cinema_id"], ["id"]
    )
    op.drop_column("tickets", "movie_showtime_id")
    op.drop_constraint(None, "movie_showtimes", type_="foreignkey")
    op.drop_column("movie_showtimes", "cinema_id")
    op.create_table(
        "spatial_ref_sys",
        sa.Column("srid", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "auth_name", sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
        sa.Column("auth_srid", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "srtext", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.Column(
            "proj4text", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.CheckConstraint(
            "(srid > 0) AND (srid <= 998999)", name="spatial_ref_sys_srid_check"
        ),
        sa.PrimaryKeyConstraint("srid", name="spatial_ref_sys_pkey"),
    )
    # ### end Alembic commands ###
