"""empty message

Revision ID: 53c47491a536
Revises: 3dd83a5ecd04
Create Date: 2022-06-13 13:49:16.040035

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = "53c47491a536"
down_revision = "3dd83a5ecd04"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.add_column("tickets", sa.Column("cinema_id", sa.Integer(), nullable=False))
    op.add_column("tickets", sa.Column("movie_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "tickets", "movies", ["movie_id"], ["id"])
    op.create_foreign_key(None, "tickets", "cinemas", ["cinema_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tickets", type_="foreignkey")
    op.drop_constraint(None, "tickets", type_="foreignkey")
    op.drop_column("tickets", "movie_id")
    op.drop_column("tickets", "cinema_id")
    op.create_table(
        "spatial_ref_sys",
        sa.Column("srid", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "auth_name", sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
        sa.Column("auth_srid", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "srtext", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.Column(
            "proj4text", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.CheckConstraint(
            "(srid > 0) AND (srid <= 998999)", name="spatial_ref_sys_srid_check"
        ),
        sa.PrimaryKeyConstraint("srid", name="spatial_ref_sys_pkey"),
    )
    # ### end Alembic commands ###
