"""empty message

Revision ID: bfd60b009b58
Revises: 53c47491a536
Create Date: 2022-06-13 14:18:56.139794

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = "bfd60b009b58"
down_revision = "53c47491a536"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table("spatial_ref_sys")
    op.drop_table("movie_distributions")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "movie_distributions",
        sa.Column("cinema_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("movie_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["cinema_id"], ["cinemas.id"], name="movie_distributions_cinema_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["movie_id"], ["movies.id"], name="movie_distributions_movie_id_fkey"
        ),
    )
    op.create_table(
        "spatial_ref_sys",
        sa.Column("srid", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "auth_name", sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
        sa.Column("auth_srid", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "srtext", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.Column(
            "proj4text", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.CheckConstraint(
            "(srid > 0) AND (srid <= 998999)", name="spatial_ref_sys_srid_check"
        ),
        sa.PrimaryKeyConstraint("srid", name="spatial_ref_sys_pkey"),
    )
    # ### end Alembic commands ###
