"""empty message

Revision ID: c6fbb542d23a
Revises: fc832ab0b343
Create Date: 2022-06-13 15:13:25.355320

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2



# revision identifiers, used by Alembic.
revision = 'c6fbb542d23a'
down_revision = 'fc832ab0b343'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.drop_constraint('movie_showtimes_cinema_id_fkey', 'movie_showtimes', type_='foreignkey')
    op.drop_column('movie_showtimes', 'cinema_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie_showtimes', sa.Column('cinema_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('movie_showtimes_cinema_id_fkey', 'movie_showtimes', 'cinemas', ['cinema_id'], ['id'])
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###
